### ISSUE TITLE
Ошибка отображения статистики пользователей.

### ISSUE THREAD

**Issue by mashchenko** [JB-SelfCompany/awg-docker-bot#2]
Бот в меню "информация о пользователе" периодически не показывает данные по последнему подключению и объему переданного трафика. Отображает  будто пользователь еще ни разу не авторизовывался на сервере.

**Comment by JB-SelfCompany** [comment]
https://github.com/JB-SelfCompany/awg-docker-bot/commit/021d5ce926690c432347181286138863605234d7
Реализован другой тип форматирования карточки клиентов. Трафик корректно отображается.
