### ISSUE TITLE
пожелания к доработке

### ISSUE THREAD

**Issue by makarovmvmv** [JB-SelfCompany/awg-docker-bot#3]
1. "Введите имя Docker-контейнера с AmneziaWG..." - желательно чтобы автоматом подтягивал
2.  В конце лучше чтобы скрипт сам все завершал без лишних опросов.

**Comment by JB-SelfCompany** [comment]
https://github.com/JB-SelfCompany/awg-docker-bot/commit/7371e7a7c43df225b2dfd2a1600b9ab40343e45b
Сделано, скрипт сам закрывается после установки. Так же, бот сам находит нужный докер контейнер и прописывает в свои настройки.
